<a href="https://colab.research.google.com/github/JahnviShukla09/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment No.- 8
## Title- Tools for EDA- Study of NumPy Library
##Jahnvi Shukla
##PRN- 25070123055
## ENTC- A3

##NumPy


In [3]:
#Declaration of NumPy
import numpy as np

a = np.array([10,20,30,40])
b = np.array([[1,2,3], [4,5,6]])
print(a)
print(b)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [4]:
#Dimension of Array
print(a.ndim)
print(b.ndim)

1
2


In [7]:
a.shape #row,column. rows-samples, columns- features

(4,)

In [6]:
b.shape

(2, 3)

In [10]:
a.dtype #datatype and bits

dtype('int64')

In [9]:
b.dtype

dtype('int64')

In [11]:
# In built functions using NumPy
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.eye((3)) #Diagonal matrix, symmetric

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [20]:
np.linspace(0,1,5) #1 is ot exclusive

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
print(b * 2)
print(a + 5)

[[ 2  4  6]
 [ 8 10 12]]
[15 25 35 45]


In [23]:
print(b) #will not change the original value

[[1 2 3]
 [4 5 6]]


In [25]:
np.mean(a) #average value

np.float64(25.0)

In [26]:
np.mean(b)

np.float64(3.5)

In [27]:
np.median(a) #middle value

np.float64(25.0)

In [28]:
np.median(b)

np.float64(3.5)

In [29]:
np.max(a)

np.int64(40)

In [30]:
np.max(b)

np.int64(6)

In [31]:
np.min(a)

np.int64(10)

In [32]:
np.min(b)

np.int64(1)

In [33]:
np.sum(a)

np.int64(100)

In [34]:
np.sum(b)

np.int64(21)